core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", index, name="index"),
    path("lottery/", lottery, name="lottery"),
    path("search/", search, name="search"),
    path("about/", about, name="about"),
    path("masthead/", masthead, name="masthead"),
    path("comp/", comp, name="comp"),
    path("contact/", contact, name="contact"),
    path("features/", features, name="features"),
    path("starr/", starr, name="starr")
]

lampoon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("read/", include("read.urls")),
    path("create/", include("create.urls")),
    path("", include("account.urls")),
    path('tinymce/', include('tinymce.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "The Harvard Lampoon"

account/models.py
from account import ACCOUNT
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from .managers import CustomUserManager
from django.utils.safestring import mark_safe

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    url_username = models.CharField(max_length=200, unique=True, help_text="harvardlampoon/@<YOUR_URL_USERNAME>/")
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_hidden = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    graduation_year = models.CharField(max_length=50)

    use_real_name = models.BooleanField(default=False)

    display_name = models.CharField(max_length=200)
    bio = models.TextField(max_length=5000, null=True, blank=True)

    profile_picture = models.ImageField(upload_to="profiles/", null=True, blank=True)

    board = models.CharField(choices=ACCOUNT.BOARD_CHOICES, max_length=20)
    year_joined = models.CharField(max_length=4, null=True, blank=True)
    positions = models.CharField(max_length=150, null=True, blank=True, help_text="Comma seperated positions")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'display_name', 'url_username']

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def profile_picture_preview(self):
        if self.profile_picture:
            return mark_safe(u"<a href='{}'><img height='300' style='border-radius: 50%;' src='{}'/></a>".format(self.profile_picture.url, self.profile_picture.url))
        else:
            return 'No Image'
    profile_picture_preview.short_description = 'Image'

    def get_name(self):
        if self.use_real_name:
            return f"{self.first_name} {self.last_name}"
        return self.display_name

ads/models.py
from django.db import models
from django.conf import settings
from . import ADS

class Ad(models.Model):
    title = models.CharField(max_length=200)
    url = models.URLField()
    image = models.ImageField(upload_to="ads/")
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    active = models.BooleanField(default=True)

    ad_type = models.CharField(choices=ADS.AD_TYPES, max_length=50)
    
    def __str__(self) -> str:
        return f"{self.title} {self.get_ad_type_display()}"

ads/views.py
from django.shortcuts import render

# Create your views here.

templates/includes/ad.html
{% load static %}
{% load ads %}

{% get_ad ad_type as ad %}
{% if ad %}
<div class="text-center mt-2">
    <a target="_blank" href="{{ad.url}}">
    <img src="{{ad.image.url}}" class="img-fluid shadow" alt="">
    </a>
</div>
{% endif %}

templates/includes/artist_profile_pic.html
{% load static %}
{% if art.custom_display_name %}
<span class="work">
    <img class="me-2 shadow" style="border-radius: 50%;" width="30" height="30" src="{% static 'images/lampy.png' %}"
        alt="">{{art.get_display_name}}</span>
{% else %}
<a class="work-link" href="{% url 'account_detail' art.artist.url_username %}">
    <img class="me-2 shadow" style="border-radius: 50%;" width="30" height="30"
        src="{% if art.artist.profile_picture %}{{art.artist.profile_picture.url}}{% else %}{% static 'images/lampy.png' %}{% endif %}" alt="">{{art.get_display_name}}</a>
{% endif %}

templates/includes/book_card.html
{% load static %}
<a class="card-link" href="{% url 'book_detail' book.pk %}">
    <div class="card shadow mb-4">
    <img src="{{book.cover_image.image.url}}" class="card-img-top" alt="">

    <div class="card-body text-center">
    <div class="mb-1 mt-2">
        <h2 class="card-title text-center mb-0">{{book.title}}</h2>
    </div>
    
    <div class="card-text">{{book.description|truncatechars_html:200|safe}}</div>
</div>
    </div>
</a>

templates/includes/footer.html
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
{% endblock %}
<footer class="footer mt-auto py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-lg-6 mx-auto">
                <div class="d-flex justify-content-center">
                    <a href="{% url 'about' %}" class="mx-2 footer-link">About</a>
                    <div class="mx-2">|</div>
                    <a href="{% url 'index' %}" class="mx-2 footer-link">Home</a>
                    <div class="mx-2">|</div>
                    {% if request.user.is_authenticated %}
                    <a class="mx-2 footer-link" href="{% url 'account_detail' request.user.url_username %}">My Profile</a>
                    <div class="mx-2">|</div>
                    <a class="mx-2 footer-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                    <a class="mx-2 footer-link" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
 

            <div class="text-center">Lampoon &copy; <script>document.write(new Date().getFullYear())</script></div>
    </div>
    </div>
</footer>

templates/includes/form.html
{% load widget_tweaks %}

{% load static %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
  {% for error in form.non_field_errors %}
    {{ error }}
  {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="form-group mb-3">
  <div class="form-label">{{ field.label }}</div>

  {% if form.is_bound %}
    {% if field.errors %}
      {% render_field field class="form-control form-default is-invalid" %}
      {% for error in field.errors %}
        <div class="invalid-feedback">
          {{ error }}
        </div>
      {% endfor %}
    {% else %}
      {% render_field field class="form-control form-default" %}
    {% endif %}
  {% else %}
    {% render_field field class="form-control form-default" %}
    
  {% endif %}

  {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
  {% endif %}
</div>
{% endfor %}

templates/includes/laugh-badge.html
{% if work.laugh_score > 0 %}
<div class="badge bg-purple ms-1">{{work.laugh_score}}</div>
{% endif %}

templates/includes/magazine_card.html
{% load static %}
<a class="card-link" href="{% url 'magazine_detail' magazine.pk %}">
    <div class="card shadow mb-4">
        <div class="img-container">
            <img src="{{magazine.cover_image.image.url}}" class="card-img-top magazine-img" alt="">
            <div class="middle">
                <h2 class="">{{magazine.title}}</h2>
            </div>
        </div>

    <div class="card-body text-center">
    <div class="mb-1 mt-2">
        <h2 class="card-title text-center mb-0">{{magazine.title}}</h2>
        <!-- <h5 class="mb-1"><div data-bs-toggle="tooltip" data-bs-placement="top" title="{{magazine.get_total_laughs}} Total Laughs" class="badge badge-laugh ms-2">{{magazine.get_total_laughs}}</div></h5> -->
    </div>
    
    <div class="card-text">{{magazine.description|truncatechars_html:200|safe}}</div>
</div>
    </div>
</a>

templates/includes/navbar.html
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}
<div id="top-navbar">
<div class="top-banner"><i class="fa fa-bell mx-2"></i>   Subscribe to the <a class="" href="https://checkout.subscriptiongenius.com/harvardlampoon.com/">Harvard Lampoon</a></div>
<div class="container my-5">
    <div class="row">
        <div class="col-3 d-flex align-items-center justify-content-start">
            <a class="social-button me-3 d-md-block d-none" href="https://www.facebook.com/theharvardlampoon/"><i class="fa fa-facebook social-icon"></i></a>
            <a class="social-button mx-3 d-md-block d-none" href="https://twitter.com/harvardlampoon"><i class="fa fa-twitter social-icon"></i></a>
            <a class="social-button mx-3 d-md-block d-none" href="https://www.instagram.com/harvardlampoon/"><i class="fa fa-instagram social-icon"></i></a>
            <a data-bs-toggle="offcanvas" class="d-md-none" href="#sideNav" role="button" aria-controls="sideNav"><img width="30" id="side-nav-image" src="{% static 'images/menu-icon.svg' %}" alt=""></a>
        </div>
        <div class="mx-auto col-6 text-center">
            <a class="" href="{% url 'index' %}">
                <img width="320" class="d-none d-md-inline" src="{% static 'images/logo.png' %}" alt="">
                <img width="180" class="d-md-none" src="{% static 'images/logo.png' %}" alt="">
            </a>
        </div>
        <div class="col-3 d-flex align-items-center justify-content-end">
              
            <a href="#search-lightbox" class="" id="" data-bs-toggle="modal" data-bs-target="#searchModal">
                <img id="search" class="shadow" width="40px" src="{% static 'images/search.svg' %}" alt="">
            </a>
        </div>
    </div>
</div>

<div class="d-flex justify-content-center my-3 d-none d-md-flex">
    <a class="nav-link {%if request.path == '/' %}active{%endif%}" href="{% url 'index' %}">Home</a>
    <a class="nav-link" href="{% url 'about' %}">About</a>
    <a class="nav-link dropdown-toggle {%if 'read' in request.path %}active{%endif%}" href="{% url 'works' %}" id="readDrop" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Read
    </a>
    <ul class="dropdown-menu shadow" aria-labelledby="readDrop">
        <li><a class="dropdown-item" href="{% url 'works' %}">Pieces</a></li>
        <li><a class="dropdown-item" href="{% url 'magazines' %}">Magazines</a></li>
        <li><a class="dropdown-item" href="{% url 'books' %}">Books</a></li>
    </ul>
    <a class="nav-link" href="{% url 'comp' %}">Comp</a>
    <a class="nav-link" href="{% url 'masthead' %}">Masthead</a>
    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
    <!-- <a class="nav-link" href="{% url 'lottery' %}">Lottery</a> -->
    {% if request.user.is_authenticated %}
    <a class="nav-link" href="{% url 'account_detail' request.user.url_username %}">My Profile</a>
    {% endif %}
</div>
</div>
  {% include 'includes/search_modal.html' %}
  {% include 'includes/sideNav.html' %}
  {% include 'includes/scroll-navbar.html' %}

<script>
    var scroll_nav = document.getElementById("scroll-navbar")
    var top_nav = document.getElementById("top-navbar")
    window.addEventListener("scroll", (e)=>{
        if (window.pageYOffset >= 262){
            scroll_nav.style.display = "block"
            scroll_nav.style.opacity = "1"
            console.log("switch to")
        }
        else{
            scroll_nav.style.display = "none"
            scroll_nav.style.opacity = "0"
            scroll_nav.classList.add("d-lg-block")
        }
    })
</script>

templates/includes/navbar_old.html
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}
<div class="top-banner"><i class="fa fa-bell mx-2"></i>   Subscribe to the <a class="" href="https://checkout.subscriptiongenius.com/harvardlampoon.com/">Harvard Lampoom</a></div>
  <nav class="navbar navbar-expand-md navbar-light mt-4">
    <div class="container">
        <div class="d-flex align-items-center col-md-3 d-none d-md-block">
            <a class="social-button mx-3" href=""><i class="fa fa-facebook social-icon"></i></a>
            <a class="social-button mx-3" href=""><i class="fa fa-twitter social-icon"></i></a>
            <a class="social-button mx-3" href=""><i class="fa fa-instagram social-icon"></i></a>
          </div>
          <div class="d-md-none">
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-md-none">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
            </ul>
          </div>
        </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="" href="{% url 'index' %}">
        <img width="320" class="d-none d-md-block" src="{% static 'images/real_logo.png' %}" alt="">
        <img width="180" class="d-md-none" src="{% static 'images/real_logo.png' %}" alt="">
    </a>
      <a href="#search-lightbox" class="lightbox epcl-search-button button circle mfp-inline col-md-3 text-end">
        <span class="fa-stack" style="font-size: 20px;">
            <i class="fas fa-circle fa-stack-2x search-circle"></i>
            <i class="fa fa-search fa-stack-1x fa-inverse"></i>
          </span>
    </a>
    </div>
    
  </nav>

templates/includes/pagination.html
{% if page_obj.has_other_pages %}
<ul class="pagination p-3 justify-content-center">
  {% if page_obj.has_previous %}
    <li><a class="page-link page-first" href="?page={{ page_obj.first }}&{{get_copy.urlencode}}">&laquo;</a></li>
  {% else %}
  {% endif %}
  {% for i in page_obj.paginator.page_range %}

    {% if page_obj.number == i %}
      <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}&{{get_copy.urlencode}}">{{ i }}</a></li>
  {% endif %}
   

  {% endfor %}

  {% if page_obj.has_next %}
    <li><a class="page-link page-last" href="?page={{ page_obj.paginator.num_pages }}&{{get_copy.urlencode}}">&raquo;</a></li>
  {% else %}
  {% endif %}
</ul>
{% endif %}

templates/includes/scroll-navbar.html
{% load static %}
<div style="display: none;" id="scroll-navbar" class="bg-white fixed-top d-none shadow">
<div class="container d-flex align-items-center py-2">
      <a class="navbar-brand me-auto" href="{% url 'index' %}">
          <img height="70" src="{% static 'images/two-ibis.svg' %}" alt="">
      </a>
        <!-- <a data-bs-toggle="offcanvas" class="d-md-none" href="#sideNav" role="button" aria-controls="sideNav"><img width="30" id="side-nav-image" src="{% static 'images/menu-icon.svg' %}" alt=""></a> -->
        <a class="nav-link {%if request.path == '/' %}active{%endif%}" href="{% url 'index' %}">Home</a>
        <a class="nav-link" href="{% url 'about' %}">About</a>
        <a class="nav-link dropdown-toggle {%if 'read' in request.path %}active{%endif%}" href="{% url 'works' %}" id="readDrop" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Read
        </a>
        <ul class="dropdown-menu shadow" aria-labelledby="readDrop">
            <li><a class="dropdown-item" href="{% url 'works' %}">Pieces</a></li>
            <li><a class="dropdown-item" href="{% url 'magazines' %}">Magazines</a></li>
            <li><a class="dropdown-item" href="{% url 'books' %}">Books</a></li>
        </ul>
        <a class="nav-link" href="{% url 'comp' %}">Comp</a>
        <a class="nav-link" href="{% url 'masthead' %}">Masthead</a>
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        <!-- <a class="nav-link" href="{% url 'lottery' %}">Lottery</a> -->
        {% if request.user.is_authenticated %}
        <a class="nav-link" href="{% url 'account_detail' request.user.url_username %}">My Profile</a>
        {% endif %}
    </div>
</div>   

templates/includes/user_card.html
{% load static %}
<a class="card-link" href="{% url 'account_detail' obj.url_username %}">
    <div class="card shadow">
        <div class="card-body text-center">
            <img src="{% if obj.profile_picture %}{{obj.profile_picture.url}}{% else %}{% static 'images/lampy_profile.png' %}{% endif %}" class="profile-picture">
            <h3 class="profile-name pt-3 mb-0 work-link">{{obj.get_name}}</h3>
            <div class="mb-0 text-muted">{{obj.get_board_display}} Board {{obj.graduation_year}}</div>
            {% if obj.bio %}
            <div class="">{{obj.bio|linebreaks|truncatechars:100}}</div>
            {% endif %}
        </div>
    </div>
</a>

templates/includes/work_card.html
{% load static %}
<a class="card-link" href="{% url 'work_detail' work.pk %}">
  <div class="card shadow" style="border: none">

    <img src="{{work.get_preview_image.image.url}}" class="card-img-top" alt="...">

    <div class="card-body">
      <h5 class="card-title text-center mb-0 align-items-center d-flex justify-content-center">{{work.title}}{% include 'includes/laugh-badge.html' %}</h5>
      <div class="work fw-bold d-flex align-items-center justify-content-center">
        {% include 'includes/writer_profile_pic.html' %}
        <span class="dot mx-2 align-self-center"></span>
        <div>{{work.created_at|date:"F Y" }}</div>
      </div>

      <div class="card-text mt-3">{{work.content|truncatechars_html:75|safe}}</div>
    </div>
  </div>
</a>

templates/includes/writer_profile_pic.html
{% load static %}
{% if work.custom_display_name %}
<div>
    <img class="shadow mx-2" style="border-radius: 50%;" width="30" height="30" src="{% static 'images/lampy.png' %}"
        alt="">{{work.get_display_name}}</div>
{% else %}
<a class="work-link" href="{% url 'account_detail' work.writer.url_username %}">
    <img class="shadow mx-2" style="border-radius: 50%;" width="30" height="30"
        src="{% if work.writer.profile_picture %}{{work.writer.profile_picture.url}}{% else %}{% static 'images/lampy.png' %}{% endif %}" alt="">{{work.get_display_name}}</a>
{% endif %}